import tkinter as tk

try:
    root = tk.Tk()
    root.mainloop()
except Exception as e:
    print(f"Ошибка: {e}")